# Stage 1: Build the Angular application
FROM node:20 AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build --prod

# Stage 2: Serve the Angular application using Nginx
FROM nginx:alpine
COPY --from=build /app/dist/image-upload-app /usr/share/nginx/html
EXPOSE 8082  
CMD ["nginx", "-g", "daemon off;"]
