version: '3.8'

services:
  backend:
    build:
      context: C:/git/convert_image_to_text/neural_convert_image_to_text/backend/python/scripts
      dockerfile: Dockerfile
    container_name: python_backend
    ports:
      - "8000:8000"

  frontend:
    build:
      context: C:/git/convert_image_to_text/neural_convert_image_to_text/frontend/angular/image-upload-app
      dockerfile: Dockerfile
    container_name: angular_frontend
    ports:
      - "8082:5000"