version: '3.8'

services:
  backend:
    build:
      context: ./backend/python/scripts
      dockerfile: Dockerfile
    container_name: python_backend
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend/angular/image-upload-app
      dockerfile: Dockerfile
    container_name: angular_frontend
    ports:
      - "8082:8082"
